import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MainLayout from "@/components/layout/MainLayout";
import I18nProvider from "./i18n-provider";
import ProgressBarClient from "@/components/layout/ProgressBarClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moomkin",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

interface SingleStatePageProps {
  params: Promise<{
    locale: string;
  }>;
  children: React.ReactNode;
}

// hi baby

export default async function RootLayout({
  children,
  params,
}: SingleStatePageProps) {
  const param = await params;
  return (
    <html lang={param.locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-6J223825M8"
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-6J223825M8');
          `}
        </Script>
        <Script id="yandex-metrika" strategy="afterInteractive">
          {`
            (function(m,e,t,r,i,k,a){
              m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
            })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=103992666', 'ym');

            ym(103992666, 'init', {ssr:true, webvisor:true, clickmap:true, ecommerce:"dataLayer", accurateTrackBounce:true, trackLinks:true});
          `}
        </Script> */}
        {/* <noscript>
          <div>
            <img src="https://mc.yandex.ru/watch/103992666" style={{ position: 'absolute', left: '-9999px' }} alt="" />
          </div>
        </noscript> */}
        <ProgressBarClient />
        <I18nProvider initialLocale={param.locale}>
          <MainLayout>{children}</MainLayout>
        </I18nProvider>
      </body>
    </html>
  );
}
